config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'hello' => 'home#index'

  resources 'memos', only: %i[index show new create]

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
  # contentカラムのバリデーションを設定する
  # presence: true - 空に出来ない
  # lenght: {maximum: 1000} - 長さは最大1000文字
  validates :content, presence: true, length: {maximum: 1000}

  # titleカラムのバリデーションを設定する
  # lenght: {maximum: 50} - 長さは最大50文字
  validates :title, length: {maximum: 50}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def index
    # すべてのメモを取得する
    @memos = Memo.all
  end

  def show
    # :idのメモを取得する
    memo_id = params[:id]
    @memo = Memo.find(memo_id)
  end

  def new
    # 空のメモを作成する
    @memo = Memo.new
  end

  def create
    # 受け入れるパラメータを定義
    # requireにはモデル名、permitにはカラム名
    memo_param = params.require(:memo).permit(:content, :title)
    # メモの中身を埋めて作成
    @memo = Memo.new(memo_param)
    # セーブする(データベースに書き込む)
    if @memo.save
      # 成功した場合はメモ一覧にリダイレクト
      redirect_to(@memo)
    else
      # エラーが発生した場合はnew(フォーム)を再表示する
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/home/index.html.erb
<h1>index.html.erb</h1>
<p>Hello, world!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/index.html.erb
<h1>メモ一覧</h1>

<ul>
  <% @memos.each do |memo| %>
    <%= link_to memo do %>
      <li><%= memo.title.blank? ? 'タイトルなし' : memo.title %>: <%= memo.content %></li>
    <% end %>
  <% end %>
</ul>

<%= link_to('新規作成', new_memo_path) %>
<%= link_to('戻る', :back) %>

app/views/memos/new.html.erb
<h1>メモ作成</h1>

<%# エラーがあったら表示する %>
<% if @memo.errors.any? %>
  <ul>
    <% @memo.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%# modelにはコントローラで作った空のメモを指定する %>
<%= form_with(model: @memo, local: true) do |form| %>
  <div class="field">
    <%# タイトルを入力するテキストフィールド(labelはその説明) %>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div class="field">
    <%# メモ内容を入力するテキストエリア(labelはその説明) %>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </div>
  <div class="actions">
    <%# 送信ボタン %>
    <%= form.submit %>
  </div>
<% end %>

<%= link_to('戻る', :back) %>

app/views/memos/show.html.erb
<h1>メモ閲覧</h1>

<h2><%= @memo.title.blank? ? 'タイトルなし' : memo.title %></h2>

<pre><%= @memo.content %></pre>

<%= link_to('戻る', :back) %>